# Generated by Django 5.2.6 on 2025-10-09 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivequestion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='drivequestions.company'),
        ),
    ]
