# Generated by Django 5.2.6 on 2025-10-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivequestions', '0002_alter_drivequestion_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivequestion',
            name='drive_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='drivequestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='drivequestion',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='drivequestions.company'),
        ),
    ]
