# Generated by Django 5.2.6 on 2025-10-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GD', 'Group Discussion'), ('APT', 'Aptitude Test'), ('TECH', 'Technical Assessment'), ('MOCK', 'Mock Interview'), ('PI', 'Personal Interview')], max_length=10)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('session', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('result_date', models.DateField()),
                ('max_marks', models.IntegerField(default=50)),
                ('min_marks', models.IntegerField(default=20)),
                ('nominee', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('courses', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
