# Generated by Django 5.2.6 on 2025-09-18 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlacementCoordinator', '0005_jobapplication_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(max_length=100)),
                ('program_type', models.CharField(choices=[('GD', 'Group Discussion'), ('APT', 'Aptitude Test'), ('TECH', 'Technical Assessment')], max_length=10)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('venue', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PlacementCoordinator.jobposting')),
            ],
        ),
    ]
