# Generated by Django 5.2.6 on 2025-10-06 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlacementCoordinator', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('GD', 'Group Discussion'), ('APT', 'Aptitude Test'), ('TECH', 'Technical Assessment'), ('MOCK', 'Mock Interview'), ('PI', 'Personal Interview')], max_length=10)),
                ('topic', models.CharField(blank=True, max_length=200, null=True)),
                ('session', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('result_date', models.DateField()),
                ('max_marks', models.IntegerField(default=50)),
                ('min_marks', models.IntegerField(default=20)),
                ('nominee', models.CharField(blank=True, max_length=100, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('courses', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='PlacementCoordinator.jobposting')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('eligible', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='training_officer.activity')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='PlacementCoordinator.jobposting')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
