# Generated by Django 5.2.5 on 2025-10-13 08:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementCoordinator', '0002_initial'),
        ('training_officer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='evaluationresult',
            unique_together={('activity', 'job', 'student')},
        ),
    ]
