# Generated by Django 5.2.7 on 2025-11-04 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PlacementCoordinator', '0002_initial'),
        ('training_officer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='PlacementCoordinator.jobposting'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='training_officer.activity'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='PlacementCoordinator.jobposting'),
        ),
        migrations.AddField(
            model_name='evaluationresult',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='evaluationresult',
            unique_together={('activity', 'job', 'student')},
        ),
    ]
