# Generated by Django 5.2.6 on 2025-09-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementCoordinator', '0003_jobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('not_interested', 'Not Interested')], default='applied', max_length=20),
        ),
    ]
