# Generated by Django 5.2.6 on 2025-09-15 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlacementCoordinator', '0004_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
